# .github/workflows/templates-ps1-use-scripts/deploy-roles.yml
name: 'Reusable Workflow: Deploy Roles'

on:
  workflow_call:
    inputs:
      pacEnvironmentSelector:
        required: true
        type: string
      planGitHubEnvironment:
        required: true
        type: string
      PAC_INPUT_FOLDER:
        required: true
        type: string
      PAC_DEFINITIONS_FOLDER:
        required: true
        type: string

env:
  PAC_INPUT_FOLDER: ${{ inputs.PAC_INPUT_FOLDER }}
  PAC_DEFINITIONS_FOLDER: ${{ inputs.PAC_DEFINITIONS_FOLDER }}

jobs:
  deployRoles:
    runs-on: ubuntu-latest
    environment: ${{ inputs.planGitHubEnvironment }}
    steps:
      # 1) Checkout the repository so scripts and definitions are available
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Download the plan artifact
      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: plans-${{ inputs.pacEnvironmentSelector }}
          path: ${{ inputs.PAC_INPUT_FOLDER }}

      # 3) Azure login using service principal JSON
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          allow-no-subscriptions: true

      # 4) Deploy roles via EPAC PowerShell script (invoke by absolute path)
      - name: Deploy Roles
        uses: azure/powershell@v2
        with:
          inlineScript: |
            & "${{ github.workspace }}/Scripts/Deploy/Deploy-RolesPlan.ps1" \
              -PacEnvironmentSelector ${{ inputs.pacEnvironmentSelector }} \
              -InformationAction Continue
          azPSVersion: 'latest'
