name: 'Reusable Workflow: Plan'

on:
  workflow_call:
    inputs:
      pacEnvironmentSelector:
        required: true
        type: string
      planGitHubEnvironment:
        required: true
        type: string
      PAC_OUTPUT_FOLDER:
        required: true
        type: string
      PAC_DEFINITIONS_FOLDER:
        required: true
        type: string
    outputs:
      deployPolicyChanges:
        description: 'The result of evaluating if a policy deployment is required'
        value: ${{ jobs.plan.outputs.deployPolicyChanges }}
      deployRoleChanges:
        description: 'The result of evaluating if a role deployment is required'
        value: ${{ jobs.plan.outputs.deployRoleChanges }}

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.planGitHubEnvironment }}
    outputs:
      deployPolicyChanges: ${{ steps.detectPlan.outputs.deployPolicyChanges }}
      deployRoleChanges: ${{ steps.detectPlan.outputs.deployRoleChanges }}

    steps:
      # 1) Checkout entire repo so Scripts/ and Helpers/ folders are available
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          allow-no-subscriptions: true

      # 3) Build the plan from the checked-out Scripts folder
      - name: Plan
        shell: pwsh
        working-directory: ${{ github.workspace }}
        run: |
          & "${{ github.workspace }}/Scripts/Deploy/Build-DeploymentPlans.ps1" `
            -PacEnvironmentSelector ${{ inputs.pacEnvironmentSelector }} `
            -PlanFolder        ${{ inputs.PAC_OUTPUT_FOLDER }} `
            -DefinitionsFolder ${{ inputs.PAC_DEFINITIONS_FOLDER }} `
            -InformationAction Continue

      # 4) Detect policy/role diffs
      - name: Detect Plan File
        id: detectPlan
        shell: pwsh
        run: |
          if (Test-Path "${{ inputs.PAC_OUTPUT_FOLDER }}") {
            Write-Output "deployPolicyChanges=yes" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
            if (Get-ChildItem "${{ inputs.PAC_OUTPUT_FOLDER }}" -Recurse -Include roles-plan.json) {
              Write-Output "deployRoleChanges=yes" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
            }
          } else {
            Write-Host "Plan not found. Skipping deploy jobs."
          }

      # 5) Upload the plan for downstream jobs
      - name: Upload Deployment Plan as Artifact
        if: steps.detectPlan.outputs.deployPolicyChanges == 'yes' || steps.detectPlan.outputs.deployRoleChanges == 'yes'
        uses: actions/upload-artifact@v4
        with:
          name: plans-${{ inputs.pacEnvironmentSelector }}
          path: ${{ inputs.PAC_OUTPUT_FOLDER }}
          if-no-files-found: error
