# .github/workflows/plan.yml
name: 'Reusable Workflow: Plan'

on:
  workflow_call:
    inputs:
      pacEnvironmentSelector:
        required: true
        type: string
      planGitHubEnvironment:
        required: true
        type: string
      PAC_OUTPUT_FOLDER:
        required: true
        type: string
      PAC_DEFINITIONS_FOLDER:
        required: true
        type: string
    outputs:
      deployPolicyChanges:
        description: 'If a policy deployment is required'
        value: ${{ jobs.plan.outputs.deployPolicyChanges }}
      deployRoleChanges:
        description: 'If a role deployment is required'
        value: ${{ jobs.plan.outputs.deployRoleChanges }}

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.planGitHubEnvironment }}
    outputs:
      deployPolicyChanges: ${{ steps.detectPlan.outputs.deployPolicyChanges }}
      deployRoleChanges: ${{ steps.detectPlan.outputs.deployRoleChanges }}

    steps:
      # 1) Checkout repo so Scripts/ and Helpers/ are available
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Azure login using service principal JSON
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          allow-no-subscriptions: true

      # 3) Debug: list Scripts folder to verify Helpers present
      - name: 'Debug: list Scripts folder'
        run: |
          echo "Workspace root: $GITHUB_WORKSPACE"
          echo "Contents of Scripts directory:"
          ls -lR "$GITHUB_WORKSPACE/Scripts"

      # 4) Build the deployment plan (loads Az modules automatically)
      - name: Plan
        uses: azure/powershell@v2
        with:
          azPSVersion: 'latest'
          inlineScript: |
            & "${{ github.workspace }}/Scripts/Deploy/Build-DeploymentPlans.ps1" `
              -PacEnvironmentSelector    ${{ inputs.pacEnvironmentSelector }} `
              -OutputFolder              ${{ inputs.PAC_OUTPUT_FOLDER }} `
              -DefinitionsRootFolder     ${{ inputs.PAC_DEFINITIONS_FOLDER }} `
              -InformationAction         Continue

      # 5) Detect if there are policy or role changes to deploy
      - name: Detect Plan File
        id: detectPlan
        shell: pwsh
        run: |
          if (Test-Path "${{ inputs.PAC_OUTPUT_FOLDER }}") {
            "deployPolicyChanges=yes" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
            if (Get-ChildItem "${{ inputs.PAC_OUTPUT_FOLDER }}" -Recurse -Include roles-plan.json) {
              "deployRoleChanges=yes" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
            }
          } else {
            Write-Host "Plan not found. Skipping deploy jobs."
          }

      # 6) Upload the plan artifact if changes exist
      - name: Upload Deployment Plan as Artifact
        if: needs.plan.outputs.deployPolicyChanges == 'yes' || needs.plan.outputs.deployRoleChanges == 'yes'
        uses: actions/upload-artifact@v4
        with:
          name: plans-${{ inputs.pacEnvironmentSelector }}
          path: ${{ inputs.PAC_OUTPUT_FOLDER }}
          if-no-files-found: error
