# .github/workflows/templates-ps1-use-scripts/remediate.yml
name: 'Reusable Workflow: Remediation'

on:
  workflow_call:
    inputs:
      pacEnvironmentSelector:
        required: true
        type: string
      planGitHubEnvironment:
        required: true
        type: string
      PAC_DEFINITIONS_FOLDER:
        required: true
        type: string

env:
  pacEnvironmentSelector: ${{ inputs.pacEnvironmentSelector }}
  PAC_DEFINITIONS_FOLDER: ${{ inputs.PAC_DEFINITIONS_FOLDER }}

jobs:
  remediation:
    runs-on: ubuntu-latest
    environment: ${{ inputs.planGitHubEnvironment }}
    steps:
      # 1) Checkout the repo so Scripts/ exist
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Azure login using service principal JSON
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          allow-no-subscriptions: true

      # 3) Invoke remediation script by absolute path
      - name: Policy Remediation
        uses: azure/powershell@v2
        with:
          inlineScript: |
            & "${{ github.workspace }}/Scripts/Operations/New-AzRemediationTasks.ps1" `
              -PacEnvironmentSelector ${{ env.pacEnvironmentSelector }} `
              -OnlyCheckManagedAssignments `
              -Interactive $false `
              -InformationAction Continue
          azPSVersion: 'latest'
